name: my first pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: uptime
          run: uptime
        - name: check no of processors
          run: nproc
  test:
    runs-on: ubuntu-latest
    steps:
        - name: hello
          run: echo "Hello!"


name: My first pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4 
      - name: Build image
        run: docker build -t kserge2001/ciportofolio .
      - name: List images
        run: docker images          